name: kalinanas

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/AysheD/apiSEC
            
            # 1. Tarik kode terbaru dari GitHub
            git pull origin main
            
            # 2. Build ulang image Docker dengan nama apisec-api
            docker build -t apisec-api .
            
            # 3. Hentikan dan hapus container lama jika sedang berjalan
            docker stop ayshe_api || true
            docker rm ayshe_api || true
            
            # 4. Jalankan container baru dengan port yang sama (8069)
            docker run -d --name ayshe_api -p 8069:8000 apisec-api
