name: kalinanas

on:
  push:
    branches:
      - main  # Berjalan otomatis saat ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/project on vps
            git pull origin main
            # Tambahkan perintah build/restart service di sini (misal: npm install & pm2 restart app)
